var myApp=angular.module("myApp",["myApp.services"]);
/*myApp.factory('dataMakerService',  function(){
	return {
		getDetailData:function(){
			return [
				{
					id:0,
					isShow:0,
					sort:0,
					name:"aa",
					detail:""
				},
				{
					id:1,
					isShow:1,
					sort:0,
					name:"bb",
					detail:""
				},
				{
					id:2,
					isShow:0,
					sort:0,
					name:"cc",
					detail:""
				},
				{
					id:3,
					isShow:0,
					sort:0,
					name:"dd",
					detail:""
				},
				{
					id:4,
					isShow:1,
					sort:1,
					name:"ee",
					detail:""
				},
				{
					id:5,
					isShow:1,
					sort:2,
					name:"ff",
					detail:"ffDetail"
				},
				{
					id:6,
					isShow:0,
					sort:0,
					name:"gg",
					detail:""
				},
				{
					id:7,
					isShow:0,
					sort:0,
					name:"hh",
					detail:""
				}
			]
		}
	}
})*/
myApp.controller("firstController", ["$scope","dataMakerService", function($scope,dataMakerService){
	$scope.data=dataMakerService.getDetailData();
	$scope.changeSort=function(){
		$scope.data[1].sort=2;
		$scope.data[4].sort=1;
		$scope.data[5].sort=0;
	}
}])